### ISSUE TITLE
Support Flow-Router or make this app router-agnostic?

### ISSUE THREAD

**Issue by dalerka** [Letladi/head-start#1]
Hi, thanks for your work! Considering the growing popularity of the Flow-Router perhaps you could switch to it instead of IR. 

There's also a package [Router-Layer](https://atmospherejs.com/nicolaslopezj/router-layer) which may help you make this app router-agnostic following the example of Orion-CMS.

**Comment by letladi** [comment]
Thanks for bringing that up. To be honest I haven't had time to look into FlowRouter, but I've been hearing good things, and it seems like many people are switching to FlowRouter. I'll check it out this week and probably make the switch.

**Comment by letladi** [comment]
Or if you have time you could make the changes and send a PR.
